### ISSUE TITLE
ASGIBrowserMiddleware does not apply when the headers are not lower cased.

### ISSUE THREAD

**Issue by trauty-is-me** [newrelic/newrelic-python-agent#1011]
**Description**
When attempting to run a server (Django/Daphne in my case), when the `content-type` header is not in lower case the `should_insert_html` function returns false.

Reviewing the Commit History this has been in place since ASGI support was introduced.

Refer to: https://asgi.readthedocs.io/en/latest/specs/www.html#http

> Header names should be lowercased, but it is not required; servers should preserve header case on a best-effort basis.

**Expected Behavior**
Headers should be case insensitve

**Comment by trauty-is-me** [comment]
I have been able to monkey patch the code for now to swap out the checks from: `if header_name == b"content-type":` to `if header_name.decode().lower()  == "content-type":` for all of the header checks.

**Comment by hmstepanek** [comment]
We will open a PR to fix this issue. Thanks for bringing it to our attention!

**Comment by hmstepanek** [comment]
This has been fixed v9.40.
