### ISSUE TITLE
boto3 not instrumented

### ISSUE THREAD

**Issue by daveisfera** [newrelic/newrelic-python-agent#1178]
**Description**
It appears that `boto3` is not instrumented and shown in the profile with current versions (I'm pretty sure it used to be)

**Expected Behavior**
`boto3` would be shown in the the summaries and the trace breakdowns

**[Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results**
I thought that maybe it was caused by the addition of `aiobotocore` support in 9.10, so I tried 9.9.1 again but I still didn't see any `boto3` or `botocore` data

**Steps to Reproduce**
1) Use `boto3` in a `django` project
2) Upload data using this module
3) Observe that no information is available

**Your Environment**
Docker image: `python:3.12.4-slim-bookworm`
new relic: `9.12`
django: `5.0.7`

**Additional context**
Uploading a file to S3 is a simple way to reproduce this issue:
https://boto3.amazonaws.com/v1/documentation/api/latest/guide/s3-uploading-files.html

**Comment by TimPansino** [comment]
Bug confirmed, `s3transfer` (not `boto3` or `botocore`) is not instrumented and is running these uploads on a background thread. Will fix in the next release by instrumenting that thread.

**Comment by hmstepanek** [comment]
This was fixed and released in v9.13.0.
