### ISSUE TITLE
Introduce a default config file location

### ISSUE THREAD

**Issue by gdubicki** [newrelic/newrelic-python-agent#123]
### Is your feature request related to a problem? Please describe.

We are automating this agent deployment using Puppet.

When we do that we can do all the operations needed for it to start working for a given app outside of the app config itself - install the package in the app's virtualenv, generate the config, restart the app. All we need to pass is the virtualenv directory and the app's systemd service name.

But then we need to add the env variable NEW_RELIC_CONFIG_FILE to the systemd service file of that app and our code gets unnecessarily complicated.

It would be much easier if the agent just had a default config file location as we run a single app per server.

### Feature Description

Make the agent try to read the config file from a default location, f.e. `/etc/newrelic/python.ini`, if the configuration is not read by any of the current methods. This way the change will be backward compatible with existing user setups.

### Describe Alternatives

We could add `NEW_RELIC_CONFIG_FILE=/etc/newrelic/python.ini` as a standard env variable in all of our Python apps systemd unit files, but I find this a rather ugly solution.

### Priority

Nice to Have

**Comment by a-feld** [comment]
That's an interesting idea! Note, the agent can be configured without any configuration file which seems like it might better fit your use case.

The only environment variable that is required is `NEW_RELIC_LICENSE_KEY` 😄 

Recommended environment variables:
* `NEW_RELIC_LICENSE_KEY` - your license key from New Relic.
* `NEW_RELIC_APP_NAME` - the name of your application
* `NEW_RELIC_LOG` - the file to direct log messages to, accepts `stdout` and `stderr` strings
* `NEW_RELIC_LOG_LEVEL` - `debug`, `info`, etc.

**Comment by gdubicki** [comment]
Hey @a-feld ! Thanks for looking into this.

However I think that I might have not been clear what I meant as what you suggest goes completely the opposite way I am suggesting. 😅

I get it that for many users and their use cases using env variables for configuring the plugin is good - I am fine with that.

But for my use case I would prefer to not have to use any env variables.

PS I can create a PR with this feature but would like to know if it would be merged before I start working on it.
