### ISSUE TITLE
Newrelic Agent 6.0.0.154 Not honoring HTTP_PROXY env vars

### ISSUE THREAD

**Issue by evanlurvey** [newrelic/newrelic-python-agent#128]
I have two identical services deployed. One is using 6.0.0.154 the other is using 5.24.0.153. 

The one on version 6 is not registering with newrelic when in a network with no default route out only proxy. It does however register when given a default route without proxy... 

The one on version 5 works as expected registering with newrelic using the proxy configured in HTTPS_PROXY env var.

**Comment by a-feld** [comment]
Interesting, that's most likely related to [this change](https://github.com/newrelic/newrelic-python-agent/commit/b709b00de6d2707807631a1edc286ff6ec7506a4) which defers loading of HTTP logic until the agent activates.

Can you provide further detail about your deployment? Are you using a WSGI server, for example? If so, which server? Which framework? Are you using popen or multiprocessing?

Can you provide debug logs showing the log line where the agent is activating -- log line: `Application was activated from:`? (you can redact most information aside from this line)

**Comment by a-feld** [comment]
Oh, also - how are you setting the `HTTPS_PROXY` env var? Are you doing this via python code modifying `os.environ`, or other?

**Comment by evanlurvey** [comment]
@a-feld we are setting them in our entrypoint.sh (this is all running in a docker container) 
Using FastAPI and gunicorn + uvicorn. No popen.

```
#!/usr/bin/env bash

export REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
export SSL_CERT_DIR=/etc/ssl/certs/

generatecerts.sh

echo "Active version: ${ACTIVE_VERSION}"

if [[ -n "$ACTIVE_VERSION" ]]; then
  proxy_host_port=http://squid-proxy:3128
  export http_proxy=$proxy_host_port
  export https_proxy=$proxy_host_port
  export no_proxy=169.254.170.2,169.254.169.254,127.0.0.1,localhost,<REDACTED>
  export HTTPS_PROXY=$https_proxy
  export HTTP_PROXY=$http_proxy
  export NO_PROXY=$no_proxy


  NR_KEY=$(get_newrelic_key.py)
  newrelic-admin generate-config $NR_KEY newrelic.ini
  sed -i "s/Python Application/e4p-notification-decorator-<REDACTED>" newrelic.ini
  NEW_RELIC_CONFIG_FILE=newrelic.ini newrelic-admin run-program gunicorn --certfile=/usr/local/share/certs/selfSigned.crt --keyfile=/usr/local/share/certs/selfSigned.key --worker-tmp-dir /dev/shm -b 0.0.0.0:443 --access-logfile - --error-logfile - --workers=2 --worker-class=uvicorn.workers.UvicornWorker --keep-alive 300 run:APP
else
  gunicorn --worker-tmp-dir /dev/shm --certfile=/usr/local/share/certs/selfSigned.crt --keyfile=/usr/local/share/certs/selfSigned.key --bind 0.0.0.0:443 --access-logfile - --error-logfile - --workers=2 --worker-class=uvicorn.workers.UvicornWorker --keep-alive 300 run:APP
fi
```

**Comment by evanlurvey** [comment]
My peer also noted that some endpoints have been broken by this latest newrelic change in fastapi. Rolling back the version of NewRelic resolved the issue

**Comment by a-feld** [comment]
Thanks for the info! I'll take a closer look once I get into the "office" (AKA open my work machine 😛 ) tomorrow.

Re: asgi changes - it's possible [some instrumentation](https://github.com/newrelic/newrelic-python-agent/compare/v5.24.0.153...v6.0.0.154#diff-32d246d21121ae56e2b8211b676d6929e888d1e2bc1e21c62e2537cc60fcbd2c) we added around asgiref may have also broken some fastapi stuff, although we didn't see a regression in the tests.  That may be a separate issue. If you have any stack traces / information around that, we'd also love to take a look!

**Comment by evanlurvey** [comment]
@a-feld sounds great! Thanks for being so responsive. If it makes it easier we can hop on a call in the AM and go over it and I can share more of the code, it's a very simple smaller app 😄 

```
Traceback (most recent call last):
  File "/app/e4p_notification_decorator/main.py", line 34, in catch_exceptions_middleware
    return await call_next(request)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 45, in call_next
    task.result()
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "<string>", line 5, in wrapper
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 201, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 148, in run_endpoint_function
    return await dependant.call(**values)
  File "/app/e4p_notification_decorator/routers/decorator_router.py", line 25, in decorate_notification_request
    notification_schema = decorate_event_data(notification_schema, push_events_request.dict())
  File "/app/e4p_notification_decorator/routers/decorator_router.py", line 37, in decorate_event_data
    decorate_event_data(schema_value, push_event_request)
  File "/app/e4p_notification_decorator/routers/decorator_router.py", line 46, in decorate_event_data
    update_with_hotel_information(notification_schema, schema_key, location_keys, picard_response)
  File "/app/e4p_notification_decorator/routers/decorator_router.py", line 56, in update_with_hotel_information
    picard_response = picard.get_hotel_information()
  File "/app/e4p_notification_decorator/client/picard.py", line 17, in get_hotel_information
    response = client.get(URL)
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 907, in get
    return self.request(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 733, in request
    return self.send(
  File "/usr/local/lib/python3.9/site-packages/newrelic/hooks/external_httpx.py", line 85, in sync_send_wrapper
    response = wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 783, in send
    hook(response)
  File "/usr/local/lib/python3.9/site-packages/newrelic/hooks/external_httpx.py", line 26, in newrelic_event_hook
    tracer.process_response(getattr(response, "status_code", None), headers)
```

**Comment by a-feld** [comment]
Ah, that looks like some sort of bug in our new `httpx` instrumentation 😞 
What is the exception at that traceback?

**Comment by a-feld** [comment]
Hi @evanlurvey - I just realized that you're setting the `HTTPS_PROXY` environment variables, but the agent uses `NEW_RELIC_PROXY_HOST`.

Give `export NEW_RELIC_PROXY_HOST=$https_proxy` a try 😄

**Comment by evanlurvey** [comment]
@a-feld I will give that a try once the httpx instrumentation is fixed. Is that something new with version 6?  I know we haven't had to do this in prev versions.

As far as the exception message it got swallowed somewhere. Once I get some time I can try and step through and find it.

**Comment by evanlurvey** [comment]
@a-feld So to make it more interesting we added the NEW_RELIC_PROXY_HOST env var and that resovled the proxy issue AND the httpx issue. But this worries me that if there is no connection to newrelic that we might get that exception.

**Comment by a-feld** [comment]
@evanlurvey There's definitely a [bug in the httpx instrumentation that we're fixing](https://github.com/newrelic/newrelic-python-agent/pull/129) -- it's not you 😄 
We're trying to get that fix out today.

**Comment by umaannamalai** [comment]
@evanlurvey We just put out a new agent release. Could you give the new version a try and let us know how that works for you?
