### ISSUE TITLE
[DT] Deprecate CAT

### ISSUE THREAD

**Issue by rr0214** [newrelic/newrelic-python-agent#170]

**Comment by rr0214** [comment]
Comment added by Andreas Can in Aha! - [View](https://newrelic.aha.io/comments/6982226010785743281)

Need confirmation from Leadership on this deprecation before completing ("completely removing CAT") the task

**Comment by ak-war** [comment]
Comment added by Andreas Can in Aha! - [View](https://newrelic.aha.io/comments/6987038011749137618)

CAT Deprecation will be announced on the DT by Defalt release.  
  
  
CAT will be EOL'd at a. later date - set by Erik Lucus
