### ISSUE TITLE
Update and document ca certificate bundles in the agent.

### ISSUE THREAD

**Issue by a-feld** [newrelic/newrelic-python-agent#178]
- [ ] Add automatic CA cert bundling flow to deploy workflow.
- [ ] Add documentation page that clearly says that **system certificates are used automatically if available** and that if the embedded bundle is relied upon, **the customer will be responsible for keeping the agent up to date**.

https://curl.se/docs/caextract.html can be used to generate bundles as part of the deploy workflow. The `cacert.pem` file would need to be written into the github actions workspace prior to calling the packaging flow.

**Comment by Ak-x** [comment]
Updated Documentation:  https://docs.newrelic.com/docs/apm/agents/python-agent/supported-features/certificate-bundle
