### ISSUE TITLE
sqlite executemany instrumentation loses data

### ISSUE THREAD

**Issue by davisagli** [newrelic/newrelic-python-agent#179]
**Description**
The hook for sqlite's executemany method processes one of its parameters in a way that can prevent it from getting passed intact to the real executemany. As a result, database operations using executemany have no effect.

Here is the current implementation: https://github.com/newrelic/newrelic-python-agent/blob/242c51a869b506d4235c8fedf024002251ac502c/newrelic/hooks/database_sqlite.py#L75-L78

If `seq_of_parameters` is a generator, then calling `list()` on it consumes the generator, and no more values will be available once the wrapped executemany receives the generator.

**Expected Behavior**
The hook should avoid consuming any values from `seq_of_parameters`, or should be sure to construct an equivalent generator to pass to the wrapped function.

**Steps to Reproduce**
Can be reproduced by running this Python script:
```python
from newrelic import agent
agent.initialize()

import sqlite3
conn = sqlite3.connect("test.db")

conn.executescript("""CREATE TABLE data (
    id integer primary key,
    value text
);
""")

conn.executemany(
    'insert into data (value) values (?)',
    ((value,) for value in range(5))
)
value_ids = {
    value: id
    for id, value in conn.execute('select id, value from data')
}

# should print 5, but prints 0 because the data was not actually inserted
print(len(value_ids))
```

**Your Environment**
Python 3.8.6
Version 6.2.0.156 of the newrelic Python agent

**Comment by umaannamalai** [comment]
Hi @davisagli - thank you for reporting this issue! We will work on getting a fix out for this in our next release.

**Comment by umaannamalai** [comment]
@davisagli We had our release go out today with a fix for this. Please let us know if you run into any other issues!
