### ISSUE TITLE
commit history and permalinks broken?

### ISSUE THREAD

**Issue by spyoungtech** [newrelic/newrelic-python-agent#2]
I have some permalinks to this repo that are now broken due to recent changes. For example this link is now a 404: https://github.com/newrelic/newrelic-python-agent/blob/v5.10.0.138/newrelic/newrelic/core/data_collector.py

The history of commits seems to also have been force-pushed over. This breaks git mirroring into our downstream custom version of this package. Additionally, all the useful git history is now gone. The oldest commit is now only 27 days ago? So when we experience issues between older versions, we cannot see the commits that happened between versions...

**Comment by rr0214** [comment]
Hi @spyoungtech. Thank you for submitting this issue.

To get the permalinks to work, please remove the the extra 'newrelic/' from the path. For example, use the link below:
[https://github.com/newrelic/newrelic-python-agent/blob/v5.10.0.138/newrelic/core/data_collector.py](https://github.com/newrelic/newrelic-python-agent/blob/v5.10.0.138/newrelic/core/data_collector.py)

We moved our code over to the new repo 27 days ago to make our agent code open source. The code however does reflect changes back to version 5.2.0. For example, this link shows the changes made between v5.2.0 and v5.8.0 [https://github.com/newrelic/newrelic-python-agent/compare/v5.2.0...v5.8.0](https://github.com/newrelic/newrelic-python-agent/compare/v5.2.0...v5.8.0) 

With the agent now open sourced, I would encourage you to submit the changes you made in your custom version back to the original repo.

Let me know if we can help.

**Comment by spyoungtech** [comment]
I see. I think I understand now what happened and the source of my confusion. Thanks for the help.
