### ISSUE TITLE
Traceback - AttributeError: 'Thread' object has no attribute 'isAlive'

### ISSUE THREAD

**Issue by cmlh** [newrelic/newrelic-python-agent#205]
**Troubleshooting**

Latest Traceback is reproduced below: 

`2021-05-07 23:17:14,735 (4/NR-Activate-Session/REDACTED) newrelic.core.agent_protocol INFO - Reporting to:` `https://rpm.newrelic.com/accounts/REDACTED/applications/REDACTED`
`INFO: Reporting to: https://rpm.newrelic.com/accounts/REDACTED/applications/REDACTED`
`Exception in thread NR-Activate-Session/REDACTED:`
`Traceback (most recent call last):` 
`  File "/app/.heroku/python/lib/python3.9/threading.py", line 954, in _bootstrap_inner` 
`    self.run()` 
`  File "/app/.heroku/python/lib/python3.9/threading.py", line 892, in run`
`    self._target(*self._args, **self._kwargs)`
`  File "/app/.heroku/python/lib/python3.9/site-packages/newrelic/core/application.py", line 531, in connect_to_data_collector`
`    activate_agent()`
`  File "/app/.heroku/python/lib/python3.9/site-packages/newrelic/core/agent.py", line 694, in activate_agent`
`    if self._harvest_thread.isAlive():`
`AttributeError: 'Thread' object has no attribute 'isAlive'`

**Your Environment**

The Python [runtime.txt](https://devcenter.heroku.com/articles/python-support#supported-runtimes) file is `python-3.9.5` and is the [latest release (3 May 2021) supported by Heroku](https://devcenter.heroku.com/changelog-items/2140).

requirements.txt lists `newrelic==6.2.0.156` which is the latest release on [PyPi](https://pypi.org/project/newrelic/#history).

**Comment by tirkarthi** [comment]
Relevant commit fix : https://github.com/newrelic/newrelic-python-agent/commit/0440969b7529d5d48d04557e70448a4f186f0f6f

**Comment by cmlh** [comment]
Should I revert to Python 3.7.10 as a workaround @tirkarthi ?

**Comment by tirkarthi** [comment]
The removal was done in Python 3.9 and python 3.8 also helps. The fix is trivial and commit seems to indicate it has been released but I have not checked source for the release.

**Comment by cmlh** [comment]
Thanks for you help @tirkarthi.

The only thing I can add is that I have a few other web applications that have been upgraded to Python 3.9.x that don't Raise this Exception for some reason 🤷‍♂️.
