### ISSUE TITLE
Django - asgi - 'NoneType' object has no attribute 'transaction_tracer'

### ISSUE THREAD

**Issue by mthipparthi** [newrelic/newrelic-python-agent#228]
**Description**
Django with asgi, quite often we are getting this error 'NoneType' object has no attribute 'transaction_tracer'. Not very consistent behaviour.

**Expected Behavior**
As mentioned in this for Tornado, https://github.com/newrelic/newrelic-python-agent/issues/19, in case of asgi as well, tranaction object is alive but settings have been nullified.

**[Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag]**

>   File "django/db/models/sql/compiler.py", line 1156, in execute_sql
    cursor.execute(sql, params)
  File "django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "newrelic/hooks/database_psycopg2.py", line 65, in execute
    **kwargs)
  File "newrelic/hooks/database_dbapi2.py", line 39, in execute
    *args, **kwargs)
  File "newrelic/api/time_trace.py", line 169, in __exit__
    self._complete_trace()
  File "newrelic/api/time_trace.py", line 410, in _complete_trace
    self.finalize_data(transaction, *exc_data)
  File "newrelic/api/database_trace.py", line 124, in finalize_data
    tt = settings.transaction_tracer

**Steps to Reproduce**
[NOTE]: # ( Please be as specific as possible. )

> newrelic-admin run-program gunicorn --workers 4 --max-requests 300 --max-requests-jitter 100 --bind 0.0.0.0:8088 -k uvicorn.UvicornWorker app.asgi:application

**Your Environment**

> newrelic - 6.0.1.155
Django - 3.1.8
uvicorn - 0.13.4

**Additional context**
If settings are nullified for whatever reason, there should be check (as done for tornado) to ignore further processing rather than rising attribute erros as it will impact high valuable business transactions.

This is the fix and it is working for us now.

> from newrelic.api.database_trace import DatabaseTrace

> def finalize_data(self, transaction, exc=None, value=None, tb=None):
>     if transaction and transaction.settings:
>         super(DatabaseTrace, self).finalize_data(
>             transaction, exc=exc, value=value, tb=tb
>         )
> 
> 
> def create_node(self):
>     if hasattr(self, 'stack_trace'):
>         return super(DatabaseTrace, self).create_node()
>     return None
> 
> 
> DatabaseTrace.finalize_data = finalize_data
> DatabaseTrace.create_node = create_node

**Comment by DmytroLitvinov** [comment]
We have the same issue.

**Comment by aleosd** [comment]
Got the same issue, fastapi/gunicorn/uvicorn setup.

**Comment by umaannamalai** [comment]
@aleosd @DmytroLitvinov @mthipparthi thank you all for reporting this! We have released a fix that should alleviate this issue in our latest agent version (v7.2.4.171). Please let us know if the problem persists or if you run into anything else after upgrading.

**Comment by DmytroLitvinov** [comment]
Hi @umaannamalai ,
Just because we downgraded our version because of that [issue](https://github.com/newrelic/newrelic-python-agent/issues/434), we receive it again.
Seems like in v7.2.4.171 it is fixed.
