### ISSUE TITLE
'Client' object has no attribute '_nr_event_hooks'

### ISSUE THREAD

**Issue by twcurrie** [newrelic/newrelic-python-agent#249]
We're observing a bug getting reported within Sentry from within the New Relic agent.

**Description**
It appears the NR agent is attempting to access a variable/attribute that has not been provided to the object: 
![image](https://user-images.githubusercontent.com/6046907/121103206-488a5c80-c7b4-11eb-9884-52678328f557.png)

**Expected Behavior**
We expect the monitoring agent to not trigger bug alerts or cause API calls to fail.

**Troubleshooting**
No troubleshooting is feasible from our end.  Our NR agent is appropriately configured.

**Steps to Reproduce**
This was triggered during a HTTP request to our application. 

**Your Environment**
Our application is asgi/uvicorn/FastAPI.  Libraries present:
- aenum=3.1.0
- aioredis=1.3.1
- alembic=1.6.5
- async-timeout=3.0.1
- certifi=2021.5.30
- chardet=4.0.0
- fastapi=0.65.1
- greenlet=1.1.0
- gunicorn=20.0.4
- h11=0.12.0
- hiredis=2.0.0
- httpcore=0.12.3
- httptools=0.1.1
- httpx=0.17.1
- idna=2.10
- importlib-metadata=4.4.0
- limits=1.5.1
- mako=1.1.4
- markupsafe=2.0.1
- newrelic=6.4.0.157
- pip=20.0.2
- psycopg2-binary=2.8.6
- pydantic=1.8.2
- python-dateutil=2.8.1
- python-editor=1.0.4
- redis=3.5.3
- requests=2.25.1
- rfc3986=1.5.0
- sentry-sdk=1.1.0
- setuptools=46.1.3
- six=1.16.0
- sniffio=1.2.0
- sqlalchemy=1.4.17
- starlette=0.14.2
- tenacity=7.0.0
- text-unidecode=1.3
- typing-extensions=3.10.0.0
- urllib3=1.26.5
- uvicorn=0.13.4
- uvloop=0.14.0
- websockets=8.1
- wheel=0.34.2
- zipp=3.4.1

**Additional context**
Part of the stack trace is available here: https://gist.github.com/twcurrie/575ab0e9d710b98e2fd133db9f7584e8

**Comment by a-feld** [comment]
Repro
```python
import asyncio

import httpx
import newrelic.agent

client = httpx.Client()

# BUG TRIGGER: Initialize is called after client is created
newrelic.agent.initialize()


@newrelic.agent.background_task()
async def main():
    with client:
        r = client.request(method="GET", url="https://www.example.org/")
    print(r)


asyncio.run(main())
```
