### ISSUE TITLE
AWS IMDS V2 Support

### ISSUE THREAD

**Issue by ericlarssen-wf** [newrelic/newrelic-python-agent#25]
### Is your feature request related to a problem? Please describe.
AWS has created a newer protocol to communicate with the Metadata server ([context](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html)), that enables clients to use a session based request which is more secure. With the idea of deprecating the usage of the V1 protocol, we rely on the agent to no longer use that authentication method.

### Feature Description
Adopt the session based authentication with the AWS metadata server.

### Describe Alternatives
None that I can think of.

### Additional context
https://krebsonsecurity.com/2019/08/what-we-can-learn-from-the-capital-one-hack/

### Priority
Please help us better understand this feature request by choosing a priority from the following options:
Must Have

**Comment by a-feld** [comment]
Hi @ericlarssen-wf -- thanks for the heads up. You can disable any communication with the AWS metadata server by setting the following in your `newrelic.ini` file:
```
utilization.detect_aws = false
```

We don't use any authentication at all when [communicating with the metadata server](https://github.com/newrelic/newrelic-python-agent/blob/d41fb461e7a4eb428fa85b0abc21734814bd7390/newrelic/common/utilization.py#L160) and any communication is only to determine the region, instance size, and instance ID.

I'm trying to understand the security implications / attack vector, can you elaborate on that?

**Comment by ericlarssen-wf** [comment]
You're correct, there is no attack vector coming from the agent itself, rather the risk of leaving the protocol v1 open on your account as there are capabilities of turning it off. The solution I am suggesting is to use an authenticated method by making a PUT request to the metadata server asking for a token, then follow up subsequent requests (in this case, just the one) with the token in the header. This is done by default when using boto3 or other language aws sdks, but there is no need to use boto3 in this use case. I have a branch of what the changes might look like. https://github.com/newrelic/newrelic-python-agent/compare/main...ericlarssen-wf:use-imds-token

A followup from your suggestion: If we decide to run `detect_aws` off, will cardinality of the metrics be removed?

**Comment by a-feld** [comment]
Ah, got it! I also consulted with some of the New Relic security folks about this and they reached the same conclusion. The metadata used to link the application with any hosts and host metadata that it's running on.

There wouldn't be any loss in cardinality from turning off AWS detection that I'm aware of.

Thanks for taking the time to make those edits, feel free to open a PR, we'd be happy to take a look! On cursory inspection, the token time doesn't have to be quite so long, 5 minutes is more than enough time (since it's only used on connect to New Relic).
