### ISSUE TITLE
Release notes not available with release

### ISSUE THREAD

**Issue by daveisfera** [newrelic/newrelic-python-agent#275]
### Is your feature request related to a problem? Please describe.
When a release is made available, the release notes aren't available (for example, this link currently gives a 404 https://docs.newrelic.com/docs/release-notes/agent-release-notes/python-release-notes/python-agent-60404161/ )

### Feature Description
Include information in the actual release definition

### Describe Alternatives
Publish the release notes before or at the same time as the release

### Additional context
Users have to keep track of the release and wait for the release notes to be made available before they can know if they need to upgrade to the release.

### Priority
Really want. It's not blocking anything, but makes version management unnecessarily complex

**Comment by umaannamalai** [comment]
Thank you for bringing this up! Going forward, we plan to post the contents of the release notes into the GitHub release so that information is readily available as soon as the release goes live.
