### ISSUE TITLE
daphne support

### ISSUE THREAD

**Issue by caleb15** [newrelic/newrelic-python-agent#29]
### Is your feature request related to a problem? Please describe.
We are considering switching to daphne from uwsgi

### Feature Description
daphne support

### Describe Alternatives
We could switch to uvicorn, which is supported by newrelic, or use a different APM

### Additional context
Add any other context here.

### Priority

[Nice to Have]

@aldenjenkins FYI

**Comment by a-feld** [comment]
Hi @caleb15, what web framework (if any) are you using with daphne?

**Comment by caleb15** [comment]
We are using django 2 currently but we will be switching to django 3 soon.
