### ISSUE TITLE
ASGI APIs

### ISSUE THREAD

**Issue by elucus** [newrelic/newrelic-python-agent#3]
Overview
ASGI stands for Asynchronous Server Gateway Interface. ASGI is a community driven Python specification (it is not officially accepted by the Python language standards) for standardizing interfaces for asyncio based network applications.
Motivation:
There is an emerging movement of customers transitioning onto asyncio based web application frameworks. Many of these frameworks implement the ASGI standard. Right now they don't have visibility into their transaction data.
By frameworks / servers implementing the ASGI standard, customers can choose network servers independently of frameworks (servers and frameworks are now pluggable).
Some examples of frameworks that utilize ASGI:
FastAPI
Django Channels
Starlette
Quart
Responder
Sanic
Servers implementing the ASGI specification:
uvicorn
hypercorn
daphne
Acceptance Criteria:
Deliver asgi_application APIs (context manager, decorator, wrapper interfaces) that can wrap a standard ASGI interface to extract web transaction data and start/end the transaction
ASGI version 1 and version 2 should be automatically supported via the same API
web sockets do not create transactions, since this can cause memory explosion for long-running transactions
long lived http/2 connections do not create transactions

Risks:
The ASGI specification is not yet accepted (or even submitted as an official proposal) by the official language. As such, the specification may change rapidly / in a way that breaks our APIs. This can introduce a maintenance burden on our team if we provide public APIs that break due to specification changes.

**Comment by a-feld** [comment]
Closed via https://github.com/newrelic/newrelic-python-agent/releases/tag/v5.18.0.148
