### ISSUE TITLE
Legacy graphql version is encountering an error.

### ISSUE THREAD

**Issue by ElementalWarrior** [newrelic/newrelic-python-agent#304]
When one of our services is requesting another of our services, we are getting an error in newrelic code

Logs from the calling service:
```
    Invalid response: {'errors': [{'message': "bind_resolve_field_v2() missing 2 required positional arguments: 'parent_info' and 'field_path'"}], 'data': None}
NoneType: None
```

Appears to stem here: https://github.com/newrelic/newrelic-python-agent/blob/4c5641c8124c8ac4dda9d078867ab90c9bc6b79f/newrelic/hooks/framework_graphql.py#L83

**Expected Behavior**
To not receive a positional arguments error.

**Steps to Reproduce**
Move from newrelic-6.4.4.161 -> newrelic-6.6.0.162

**Your Environment**
Running flask with graphene

Here is our pinned versions
Flask==1.1.1
graphql-relay==0.5.0 
Flask-GraphQL==1.4.1
graphene==1.4.1
graphql-core==1.1.0
graphene-sqlalchemy==1.1.1

**Additional context**
This became an issue after the newrelic package version was updated.

**Comment by umaannamalai** [comment]
Hi @ElementalWarrior - thank you for reporting this issue! We are working on a fix and will have it out in our upcoming release.
