### ISSUE TITLE
Agent crashes in FIPS mode

### ISSUE THREAD

**Issue by bixbarton** [newrelic/newrelic-python-agent#32]
When using the agent on a FIPS enabled Linux (such as RHEL) the agent errors

**Description**
Running RHEL 7.9 with FIPS
Our logs are showing the newrelic-python-agent erroring
Reporting problems traced down to 

```
newrelic/common/encoding_utils.py\", 
line 267, 
in generate_path_hash
path_hash = (rotated ^ int(md5(name).hexdigest()[-8:], base=16))

ValueError: [digital envelope routines: EVP_DigestInit_ex] disabled for fips
```

**Expected Behavior**
MD5 should not be used

**[Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results**
```
Traceback (most recent call last):
  File \"/home/myapp/p36venv/lib64/python3.6/site-packages/aiohttp/web_protocol.py\", line 418, in start
    resp = await task
  File \"/home/myapp/p36venv/lib64/python3.6/site-packages/newrelic/common/async_proxy.py\", line 120, in send
    return self.__wrapped__.send(value)
  File \"/home/myapp/p36venv/lib64/python3.6/site-packages/newrelic/common/async_proxy.py\", line 98, in __exit__
    self.transaction.__exit__(None, None, None)
  File \"/home/myapp/p36venv/lib64/python3.6/site-packages/newrelic/api/transaction.py\", line 553, in __exit__
    path_hash=self.path_hash,
  File \"/home/myapp/p36venv/lib64/python3.6/site-packages/newrelic/api/transaction.py\", line 722, in path_hash
    path_hash = generate_path_hash(identifier, seed)
  File \"/home/myapp/p36venv/lib64/python3.6/site-packages/newrelic/common/encoding_utils.py\", line 267, in generate_path_hash
    path_hash = (rotated ^ int(md5(name).hexdigest()[-8:], base=16))
ValueError: [digital envelope routines: EVP_DigestInit_ex] disabled for fips
```

**Steps to Reproduce**
Run newrelic agent inside a FIPS-enabled RHEL OS

**Your Environment**
RHEL 7.9 FIPS
Python 3.6.8
newrelic-5.16.2.147-cp36-cp36m-manylinux2010_x86_64.whl

**Additional context**
Has nobody else ever encountered this?

**Comment by a-feld** [comment]
Really sorry this sat for so long! 🤦 

The use of md5 is related to cross application tracing which is a pseudo-implementation of distributed tracing that has been superseded by New Relic's distributed tracing features. Disabling cross application tracing should resolve this error.

In your `newrelic.ini`, set `cross_application_tracer.enabled = false`

Example:
```ini
[newrelic]
cross_application_tracer.enabled = false
```
