### ISSUE TITLE
GTSE - documentation tickets

### ISSUE THREAD

**Issue by ak-war** [newrelic/newrelic-python-agent#368]
**SSC documentation:**

SSC doesn't properly ignore error_collector.ignore_classes
Github link: https://github.com/newrelic/newrelic-python-agent/issues/274

**GTSE tickets:**

The following are documentation issues raised by the GTSE team. This MMF addresses fixing those documentation issues for the Python agent. A spike will be needed to identify specific documentation to be updated for the below tickets. These tickets were in the July 21 support/management discussion slides (slide 21)

1. Agent install issues
https://newrelic.zendesk.com/agent/tickets/460261 - Heroku env, perhaps clearer documentation could have prevented this., customer unable to install
https://newrelic.zendesk.com/agent/tickets/460965 - Customer was not able to install agent and get it working, they needed to upgrade their environment - clearer documentation could have prevented this. 

2. Missing Data
https://newrelic.zendesk.com/agent/tickets/460429 - Customer not understanding how to use transaction_tracer.function_trace, clearer documentation could have prevented this. 
https://newrelic.zendesk.com/agent/tickets/460772 - Seems to be a misunderstanding of events vs metrics (in UI), perhaps clearer docs on where to find diff data types

3. Add Recommended metric/span - from Github
https://github.com/newrelic/newrelic-opencensus-exporter-python/issues/7

**Comment by Ak-x** [comment]
Completed per https://docs.newrelic.com/docs/apm/agents/python-agent/supported-features/certificate-bundle
