### ISSUE TITLE
Wrong instructions in v6.10.0.165 release notes re: logger propagation

### ISSUE THREAD

**Issue by rittneje** [newrelic/newrelic-python-agent#372]
https://docs.newrelic.com/docs/release-notes/agent-release-notes/python-release-notes/python-agent-61000165/#changes

> To reverse this behavior, in your application at any point you can run `logging.getLogger("newrelic").propagate = False`

I assume that was supposed to say `logging.getLogger("newrelic").propagate = True`, as that would restore the original behavior. Also, it isn't really true that you can do it at any point - presumably it needs to happen after `import newrelic`.

**Comment by TimPansino** [comment]
Good catch, on the second point that's fair for customers manually initializing the agent. For the majority of users on the newrelic-admin wrapper that's not an issue, but I'll update this to reflect that
