### ISSUE TITLE
TypeError newrelic.core.stats_engine in record_custom_metric

### ISSUE THREAD

**Issue by dashsatish** [newrelic/newrelic-python-agent#399]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )
TypeError in newrelic core engine

**Description**
[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )
There are errors getting flooded in our system for this.

**Expected Behavior**
[NOTE]: # ( Tell us what you expected to happen. )
No type errors should have been present.

**[Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results**
[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )
```
unsupported operand type(s) for ** or pow(): 'NoneType' and 'int'
```
```
The merging of custom metric sample ["Memory/Physical/Utilization",null] from data source "Memory Usage" has failed. Validate the format of the sample. If this issue persists then please report this problem to the data source provider or New Relic support for further investigation.
```

**Steps to Reproduce**
[NOTE]: # ( Please be as specific as possible. )
[TIP]:  # ( Link a sample application that demonstrates the issue. )

**Your Environment**
[TIP]:  # ( Include as many relevant details about your environment as possible including the running version of New Relic software and any relevant configurations. )
newrelic==7.0.0.166
ENV=Production

**Additional context**
[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )
We have a gunicorn workers running as well as non-web (long running python processes) background processes in our container. Both are associated with newrelic.

**Comment by TimPansino** [comment]
Hi @dashsatish, have you opened this as a ticket through New Relic support? If not I'd like to have our support staff engage with you and gather some information for us to start debugging this.

First and foremost though, do you have the line number from the traceback for that exception message? That would be a good place for us to start.
