### ISSUE TITLE
Runtime instrumentation error. Request context propagation failed. No trace with id {ID}. Report this issue to New Relic support.

### ISSUE THREAD

**Issue by DmytroLitvinov** [newrelic/newrelic-python-agent#434]
Hi there,
After upgrading from version **7.2.2.169** to **7.2.4.171**, we started to receive a lot of events (459k) in our Sentry with the next message:
> Runtime instrumentation error. Request context propagation failed. No trace with id 139701399167680. Report this issue to New Relic support.

We are using the next tech stack:
* Python v.3.8.12
* Django v3.2.9
* Django Channels v3.0.4
* New Relic v7.2.4.171

Command which we run to start our gunicorn:
`newrelic-admin run-program gunicorn asgi -k uvicorn.workers.UvicornWorker`

Seems like it was introduced after [that PR](https://github.com/newrelic/newrelic-python-agent/pull/420)

As a temporary solution, we downgrade our version to **7.2.2.169**.

**Comment by umaannamalai** [comment]
Hi @DmytroLitvinov! Thank you for reporting this. Would you be able to open this as a ticket with New Relic support? This will allow our support engineers to work directly with you to gather logging and other relevant information that will help us to debug this issue.

**Comment by DmytroLitvinov** [comment]
Hi @umaannamalai ,
Created [new topic](https://discuss.newrelic.com/t/runtime-instrumentation-error-request-context-propagation-failed-no-trace-with-id/169132) in forum.

**Comment by zodiacfireworks** [comment]
Same error here

![image](https://user-images.githubusercontent.com/4976355/148472184-f10dc349-8141-4a51-bc67-350d4779f330.png)
![image](https://user-images.githubusercontent.com/4976355/148472250-ba264207-819d-454b-9d6b-98b134e8b38d.png)

I'm running with daphne as follows

newrelic-admin run-program daphne -b 0.0.0.0 -p 8000 application.asgi:application --access-log - --verbosity 3

channels==3.0.4
daphne==3.0.2
django==3.2.9
newrelic==7.2.4.171

**Comment by zodiacfireworks** [comment]
Same error here

![image](https://user-images.githubusercontent.com/4976355/148472797-647ecf2b-a5af-4c8f-b0fb-0cf45c90e409.png)
![image](https://user-images.githubusercontent.com/4976355/148472250-ba264207-819d-454b-9d6b-98b134e8b38d.png)

I'm running with daphne as follows

newrelic-admin run-program daphne -b 0.0.0.0 -p 8000 application.asgi:application --access-log - --verbosity 3

channels==3.0.4
daphne==3.0.2
django==3.2.9
newrelic==7.2.4.171

**Comment by vitornere** [comment]
Same error here
`(45/ThreadPoolExecutor-0_0) newrelic.core.context ERROR - Runtime instrumentation error. Request context propagation failed. No trace with id 140476278928032. Report this issue to New Relic support.`

```
fastapi==0.70.1
newrelic==7.2.4.171
uvicorn==0.16.0
```

`NEW_RELIC_CONFIG_FILE=newrelic.ini newrelic-admin run-program uvicorn app:app --host 0.0.0.0 --port 5000 --log-level info --workers 5`

**Comment by TimPansino** [comment]
Should be fixed with #441. Feel free to reopen if this issue still occurs on versions `>7.4`

**Comment by dacevedo12** [comment]
This just happened to me.

Using
```
newrelic==7.10.0.175
starlette==0.17.1
gunicorn==20.1.0
uvicorn==0.17.4
```

`newrelic-admin run-program gunicorn 'app.app:APP'`

`newrelic.core.context ERROR - Runtime instrumentation error. Request context propagation failed. No context attached to request. Report this issue to New Relic support.`

**Comment by dacevedo12** [comment]
Related to #468?

**Comment by dacevedo12** [comment]
Tried updating starlette to 0.19.0, but no improvement.
Manual instrumentation doesn't change anything either.

Had to go all the way back to 7.2.2.169, that version doesn't fail.
Just to clarify, I'm not using FastAPI, just starlette
