### ISSUE TITLE
Link is broken to Python Agent configuration

### ISSUE THREAD

**Issue by DmytroLitvinov** [newrelic/newrelic-python-agent#435]
Link http://newrelic.com/docs/python/python-agent-configuration is broken (404 error). That link is mentioned [here](https://github.com/newrelic/newrelic-python-agent/blob/ee7d05325b35325379c8e77b28b6b395d6d94ce5/newrelic/newrelic.ini#L18).

**Comment by umaannamalai** [comment]
Thanks for pointing this out @DmytroLitvinov! We will get that updated shortly.
