### ISSUE TITLE
ImportWarning on Python 3.10

### ISSUE THREAD

**Issue by pcarn** [newrelic/newrelic-python-agent#436]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

**Description**
[NOTE]: # ( Describe the problem you're encountering. )
There's an ImportWarning showing when importing newrelic.agent on Python 3.10

**Expected Behavior**
[NOTE]: # ( Tell us what you expected to happen. )
I expect there not to be a warning

**[Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results**
[NOTE]: # ( Provide any other relevant log data. )
N/A

**Steps to Reproduce**
[NOTE]: # ( Please be as specific as possible. )
Use Python 3.10, `python -Wd`
`import newrelic.agent`
`>>> import newrelic.agent
<frozen importlib._bootstrap>:914: ImportWarning: ImportHookFinder.find_spec() not found; falling back to find_module()
`

**Your Environment**
Python 3.10

**Additional context**
Needs find_spec() here https://github.com/newrelic/newrelic-python-agent/blob/f99da493986f24a588af50e197bbe62f5ad6332a/newrelic/api/import_hook.py#L171

**Comment by staticfox** [comment]
We're also running in to this, it's preventing us from using `-W error` to trace other warnings as we're having to handle agent initialization first.

**Comment by TimPansino** [comment]
Fixed in #437
