### ISSUE TITLE
Epic: Python Logging

### ISSUE THREAD

**Issue by Ak-x** [newrelic/newrelic-python-agent#439]

**Comment by iamr0b0tx** [comment]
I have been looking for an application-level logs handler for python(Django) in the new relic agent and I haven't found any. Can someone help with this?

All I need is a handler that implements `logging.Handler` and forwards logs to newrelic(probably via the API)

**Comment by Ak-x** [comment]
Closing per release: https://docs.newrelic.com/docs/release-notes/agent-release-notes/python-release-notes/python-agent-71200176/
