### ISSUE TITLE
ModuleNotFoundError: No module named 'pwd' (Windows)

### ISSUE THREAD

**Issue by pnvnd** [newrelic/newrelic-python-agent#440]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

# Description
ModuleNotFoundError in Windows due to `pwd` not being found.  Can this be changed to `getpass` instead?  It works in Windows, Linux, and macOS.  Here are two files that are affected:

[newrelic-python-agent\newrelic\admin\record_deploy.py](https://github.com/newrelic/newrelic-python-agent/blob/main/newrelic/admin/record_deploy.py)
[newrelic-python-agent\tests\testing_support\db_settings.py](https://github.com/newrelic/newrelic-python-agent/blob/main/tests/testing_support/db_settings.py)

# Expected Behavior
Expecting the script to run without issues in both Windows, Linux, and macOS.

# Steps to Reproduce
`newrelic-admin generate-config <YOUR_LICENSE_KEY> newrelic.ini`

```
Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    import pwd
ModuleNotFoundError: No module named 'pwd'
```

# Environment
Windows 10
Python 3.9.7 and Python 3.8.10

# Potential Fix
For `newrelic-python-agent\newrelic\admin\record_deploy.py` instead of

```python
import pwd

if user is None:
    user = pwd.getpwuid(os.getuid()).pw_gecos
```
Change it to 
```python
import getpass

if user is None:
    user = getpass.getuser()
```

For `newrelic-python-agent\tests\testing_support\db_settings.py` instead of

```python
import pwd

USER = pwd.getpwuid(os.getuid()).pw_name
```
change it to
```python
import getpass

USER = getpass.getuser()
```

**Comment by TimPansino** [comment]
We do not support Windows with the Python agent and have no plans to do so in the future.
