### ISSUE TITLE
python agent reporting handled exceptions as unhandled

### ISSUE THREAD

**Issue by sandeep2rawat** [newrelic/newrelic-python-agent#442]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

**Description**
The agent is reporting handled exceptions of Django Rest Framework's. From the [Docs](https://www.django-rest-framework.org/api-guide/exceptions/#exception-handling-in-rest-framework-views), subclasses of `APIException` are handled.

I am raising `rest_framework.exceptions.AuthenticationFailed`  during custom authentication as suggested by [DRF](https://www.django-rest-framework.org/api-guide/authentication/#custom-authentication). Which is the subsclass of the APIException. Any subclass of APIException is handled by the DRF, which returns the proper response with corresponding status code. Hence these exceptions are created to be raise in the code.

**Expected Behavior**
The handled exceptions of the framework should not be reported by the client.

**Steps to Reproduce**
This is the authentication code.

```python
from rest_framework.authentication import BaseAuthentication
from rest_framework.exceptions import AuthenticationFailed
class UserAuthorization(BaseAuthentication):
    """
    Custom user authentication class.
    """

    def authenticate(self, request):
        if "Authorization" not in request.headers:
            raise AuthenticationFailed(
                {"message": "Invalid token"},
            )
        pass  # auth code
```
Here is the uwsgi `ini` file.
```ini
eval = import newrelic.agent; from config.wsgi import application; newrelic.agent.initialize('/etc/newrelic/newrelic.ini');  application = newrelic.agent.WSGIApplicationWrapper(application)
```

And here is the `wsgi.py` file's content to run newrelic client.

```python
import os
import sys
import environ

from django.core.wsgi import get_wsgi_application

app_path = os.path.abspath(
    os.path.join(os.path.dirname(os.path.abspath(__file__)), os.pardir)
)
sys.path.append(os.path.join(app_path, "project-path"))
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings.production")

env = environ.Env()
# OS environment variables take precedence over variables from .env
env.read_env(os.path.join(app_path, ".env"))

application = get_wsgi_application()
```

**Your Environment**
`newrelic==5.14.*`
Ubuntu 18.04.5 LTS (GNU/Linux 5.4.0-1060-aws x86_64)

**Additional context**
Similar problem wrt [Tastiepi framework](https://discuss.newrelic.com/t/python-agent-reporting-handled-exceptions-as-unhandled/50209).

**Comment by kyle-mccarthy** [comment]
I am also seeing this behavior with flask, even though I call [register_error_handler](https://flask.palletsprojects.com/en/2.1.x/api/#flask.Flask.register_error_handler).
