### ISSUE TITLE
Wheel support for linux aarch64[arm64]

### ISSUE THREAD

**Issue by odidev** [newrelic/newrelic-python-agent#53]
**Summary**
Installing newrelic on aarch64 via pip using command "pip3 install newrelic" tries to build wheel from source code

**Problem description**
newrelic doesn't have wheel for aarch64 on PyPI repository. So, while installing newrelic via pip on aarch64, pip builds wheel for same resulting in it takes more time to install newrelic. Making wheel available for aarch64 will benefit aarch64 users by minimizing newrelic installation time.

**Expected Output**
Pip should be able to download newrelic wheel from PyPI repository rather than building it from source code.

@newrelic-team, please let me know if I can help you building wheel/uploading to PyPI repository. I am curious to make newrelic wheel available for aarch64. It will be a great opportunity for me to work with you.

**Comment by a-feld** [comment]
A few questions regarding this!

The wheels are compiling native [wrapt](https://github.com/GrahamDumpleton/wrapt) extensions and [certain internal c extensions](https://github.com/newrelic/newrelic-python-agent/blob/main/newrelic/common/_monotonic.c).

1. Wrapt doesn't appear to test on arm (see [travis](https://travis-ci.org/github/GrahamDumpleton/wrapt). Additionally, we don't test our native c extensions with arm. Do you think we'll encounter problems if we compile and ship arm binaries?
2. We use github actions to deploy our wheels. Does github actions provide an arm runner to build the binaries?
3. Our github flows use the `setup-python` action which downloads binaries from [here](https://github.com/actions/python-versions/releases). I don't see aarch64 binaries there. Do you know if there are plans to support aarch64 there?

**Comment by odidev** [comment]
@a-feld thanks for your quick response. Please find my answers inline-

> Wrapt doesn't appear to test on arm (see travis). Additionally, we don't test our native c extensions with arm. Do you think we'll encounter problems if we compile and ship arm binaries?

I ran Wrapt travis-ci job on arm64 for python3.7 and it ran successful. I think we wouldn't encounter any problems

> We use github actions to deploy our wheels. Does github actions provide an arm runner to build the binaries?

We can use qemu to run arm64 builds on x86_64 machine

> Our github flows use the setup-python action which downloads binaries from here. I don't see aarch64 binaries there. Do you know if there are plans to support aarch64 there?

I will work on making setup-python binaries available for arm64.
