### ISSUE TITLE
sys.modules: dictionary changed size during iteration

### ISSUE THREAD

**Issue by rabbit-aaron** [newrelic/newrelic-python-agent#538]
[NOTE]: We run newrelic with Django 3.1 with gunicorn 19.10. and this error was reported to our sentry.

**Description**
error here: https://sentry.io/share/issue/a4034deafee44a6995dcb0958ef0d3a8/
Similar issues discussed in python 3.7 pickle: https://bugs.python.org/issue40327

**Steps to Reproduce**
not sure

**Your Environment**
see the sentry link above

**Suggestions**
Rather than iterating directly over sys.modules, iterate over a copy like what pickle is doing in after py3.8:
for i in sys.modules.copy().items()
https://github.com/python/cpython/blob/3.10/Lib/pickle.py#L342

**Comment by rabbit-aaron** [comment]
never mind, our version of new relic was old.

**Comment by TimPansino** [comment]
Out of curiosity, what version was causing that issue?

**Comment by rabbit-aaron** [comment]
> Out of curiosity, what version was causing that issue?

4.20.1.121
