### ISSUE TITLE
Add python app modules version information to the data published to agent_lifecycle_event

### ISSUE THREAD

**Issue by ak-war** [newrelic/newrelic-python-agent#542]
Atm python agent is publishing information about modules (like numpy) but missing versions. Afaik this information is present on runtime can be fetched and sent as attribute map for the update to the agent_lifecycle_event topic. The Python APM agent doesn't report library versions, so we can't do CVE analysis on python dependencies yet. The python agent doesn't capture the version of installed modules, which prevents us from doing security analysis on 3rd party dependencies in python services.

**Comment by hmstepanek** [comment]
Possible implementation [here](https://github.com/newrelic/newrelic-python-agent/tree/capture-module-versions).
