### ISSUE TITLE
Runtime instrumentation error. Attempt to drop the root when it is not the current trace.

### ISSUE THREAD

**Issue by corno93** [newrelic/newrelic-python-agent#544]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

**Description**
I've seen this error log a few times on my Django app. 
Its only just started occurring after upgrading new-relic from `4.20.1.121` to `7.10.0.175`. 
In the last 3 days its occurred 4 times. 

**Expected Behavior**
Not printing the error log.

**Steps to Reproduce**
Honestly not sure. It seems to happen randomly. However each time it has occurred its because we've received an API request on an endpoint. 

**Your Environment**
Please see the shared Sentry alert for the traceback and environment details. 
https://sentry.io/share/issue/664ed124a3d048b0a005105fa93fdd28/
Some highlights:
- django 3.1.14
- newrelic 7.10.0.175
- gunicorn 19.10.0
- wagtail 2.15.5

<br class="Apple-interchange-newline">

**Additional context**
I've seen many similar posts online and most of the recommendations have been upgrading newrelic to `7.x`, so I thought I should probably report this since we're already on `7.10`. 
Note we've only had this occur 4 times in 3 days. Ive seen other posts, [here](https://discuss.newrelic.com/t/python-runtimeerror-not-the-current-trace-report-this-issue-to-new-relic-support/153306), about it constantly occurring

**Comment by lrafeei** [comment]
Hello--

Can you confirm whether there are any actual unwanted error events being sent up by the agent or is it just that the error in the log is being generated?  If it's the latter, it’s just the sentry logging integration capturing the call to logger.exception() and reporting it as a handled error event.

**Comment by corno93** [comment]
I believe its just the log
Where else can I see these actual unwanted error events? I cant see anything else in Sentry nor NR
What would you recommend?

I know its just a log and I can filter the event in Sentry and in our app however it seems odd to just ignore an error log

Interestingly we have not seen it again in the last 7 days...
