### ISSUE TITLE
Today installation of newrelic==6.2.0.156 suddenly started to fail on Python 3.5.10

### ISSUE THREAD

**Issue by piqoni** [newrelic/newrelic-python-agent#572]
**Description**
We are using Python 3.5.10 and newrelic==6.2.0.156 fine for more than a year, including yesterday. But only today installation started to fail with the following error: Why did this work before, we haven't changed anything. 

```
#0 359.4 Collecting newrelic==6.2.0.156
#0 359.4   Downloading newrelic-6.2.0.156.tar.gz (796 kB)
#0 359.9     ERROR: Command errored out with exit status 1:
#0 359.9      command: /usr/local/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-u7lnfwmq/newrelic_8b09d9b5691c4a06bc2296253d813028/setup.py'"'"'; __file__='"'"'/tmp/pip-install-u7lnfwmq/newrelic_8b09d9b5691c4a06bc2296253d813028/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-x1au3eld
#0 359.9          cwd: /tmp/pip-install-u7lnfwmq/newrelic_8b09d9b5691c4a06bc2296253d813028/
#0 359.9     Complete output (5 lines):
#0 359.9     Traceback (most recent call last):
#0 359.9       File "<string>", line 1, in <module>
#0 359.9       File "/tmp/pip-install-u7lnfwmq/newrelic_8b09d9b5691c4a06bc2296253d813028/setup.py", line 23, in <module>
#0 359.9         'The New Relic Python agent only supports Python 2.7 and 3.6+.'
#0 359.9     AssertionError: The New Relic Python agent only supports Python 2.7 and 3.6+.
#0 359.9     ----------------------------------------
#0 359.9 WARNING: Discarding https://files.pythonhosted.org/packages/63/9e/e3e8ea3c1682dc
```

**Expected Behavior**
It should install without errors

**Your Environment**
Linux 5.11.0-1020-aws #21~20.04.2-Ubuntu SMP Fri Oct 1 13:03:59 UTC 2021 x86_64 GNU/Linux

**Additional context**
[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )

**Comment by TimPansino** [comment]
This version hasn't supported Python 3.5 ever, and hasn't been touched since it was released.

There's a small bug in the setup.py file that doesn't exclude 3.5 from the Python requires, but it is excluded by the assert statement at the top.

My guess is that your version of pip now uses that properly and won't install from source. There's nothing for us to do on our end.

I would highly recommend updating your version of Python to 3.7+ and adopting newer versions of the agent.
