### ISSUE TITLE
Why doesn't the new-relic-admin support nonced CSP? 

### ISSUE THREAD

**Issue by allen-munsch** [newrelic/newrelic-python-agent#580]
https://github.com/newrelic/newrelic-python-agent/blob/242c51a869b506d4235c8fedf024002251ac502c/newrelic/api/asgi_application.py#L172

Seems weird that the default would be "'unsafe-inline'"?

- https://github.com/newrelic/newrelic-python-agent/blob/242c51a869b506d4235c8fedf024002251ac502c/newrelic/api/html_insertion.py#L32
- https://github.com/newrelic/newrelic-python-agent/blob/242c51a869b506d4235c8fedf024002251ac502c/newrelic/api/html_insertion.py#L49

- https://github.com/newrelic/newrelic-python-agent/blob/ad65494033a6aef95fa2cd10b49ae73cb4c612ed/newrelic/api/web_transaction.py#L42-L44

Any suggestions?

- https://docs.newrelic.com/docs/apm/agents/python-agent/python-agent-api/disablebrowserautorum-python-agent-api/
- https://discuss.newrelic.com/t/content-security-policy-and-browser-injection/2629

- https://github.com/newrelic/newrelic-python-agent/blob/ad65494033a6aef95fa2cd10b49ae73cb4c612ed/newrelic/api/web_transaction.py#L402-L403

Similar:

- https://github.com/newrelic/newrelic-ruby-agent/issues/332
- https://github.com/newrelic/newrelic-ruby-agent/pull/673/files
-

**Comment by aaroncameron-wk** [comment]
As linked above, this has been [implemented](https://github.com/newrelic/newrelic-ruby-agent/pull/673) in the Ruby agent so would appear to be fairly trivial to implement for the Python agent as well. As far as I've seen, the reasoning for not doing this so far hinges on an assumption that it would involve breaking compatibility with outdated browsers, although that's not necessarily true or even important to many people, as expressed by many over 6 years [in this thread.](https://discuss.newrelic.com/t/content-security-policy-and-browser-injection/2629/59)

**Comment by allen-munsch** [comment]
It's not stale?

**Comment by joshuata** [comment]
This should not be marked as stale as it is a security focused feature request

**Comment by allen-munsch** [comment]
+1

**Comment by allen-munsch** [comment]
+1

**Comment by joshuata** [comment]
This should still be open as it is a security issue. I am seriously considering dropping newrelic due to the lack of movement on this

**Comment by Ak-x** [comment]
Hello @joshuata, we will get this effort scoped out on our teams end and determine when we can add this to our upcoming releases.

cc: @ak-war

**Comment by allen-munsch** [comment]
@Ak-x Thank you!

**Comment by jimleroyer** [comment]
Our team using NewRelic would really like support for this. We cannot use NewRelic on the front-end at the moment due to its lack of configuration options to align with our CSP and our requirement to use a nonce. I feel let down as other agent implementations support it except the Python one. 

Hope you folks can include this one in! 🤞

**Comment by allen-munsch** [comment]
@TimPansino Thank you! Happy Holidays. :fireworks:
