### ISSUE TITLE
psycopg3 support

### ISSUE THREAD

**Issue by alexeyshockov** [newrelic/newrelic-python-agent#585]
Hey, thanks for the great monitoring integration! [psycong3 was released in October 2021](https://www.psycopg.org/), do you have any plans to support it? Would be really nice to have a hook for this lib, as it brings a lot of useful features.

**Comment by gushecht** [comment]
Hi @alexeyshockov!  I'll start by saying that I am not an expert of psycopg3, or New Relic, or even Python, but we came across this problem today and also this issue that you opened.  

Perhaps you've solved this already, but, if not, here's how I addressed it.

For context, `startup.py` is the entry point for our web server.

startup.py
```py
import psycopg
from newrelic_custom_instrumentation import instrument_psycopg3_async_cursor
instrument_psycopg3_async_cursor(psycopg)

# ... loads of other unrelated stuff
```

newrelic_custom_instrumentation.py
```py
from newrelic.api.database_trace import (
    DatabaseTrace,
    enable_datastore_instance_feature,
    register_database_client,
)
from newrelic.common.object_wrapper import wrap_function_wrapper


# TODO – I'm not certain we're getting everything we want out of this – I based it off database_asyncpg
class PostgresApi(object):
    @staticmethod
    def _instance_info(addr, connected_fut, con_params, *args, **kwargs):
        if isinstance(addr, str):
            host = "localhost"
            port = addr
        else:
            host, port = addr

        return host, str(port), getattr(con_params, "database", None)

    @classmethod
    def instance_info(cls, args, kwargs):
        return cls._instance_info(*args, **kwargs)


register_database_client(
    PostgresApi,
    "Postgres",
    quoting_style="single+dollar",
    instance_info=PostgresApi.instance_info,
)
enable_datastore_instance_feature(PostgresApi)


# TODO – Similarly, there may be more things we can pass to DatabaseTrace
async def wrap_execute(wrapped, instance, args, kwargs):
    query, params = args
    with DatabaseTrace(
            query,
            database_name=instance.connection.info.dbname,
            dbapi2_module=PostgresApi,
            host=instance.connection.info.host,
            port_path_or_id=instance.connection.info.port,
            source=instance.execute,
            sql_parameters=params,
    ):
        return await wrapped(*args, **kwargs)


def instrument_psycopg3_async_cursor(module):
    wrap_function_wrapper(module, "AsyncCursor.execute", wrap_execute)
```

As you see in my TODO comments above, I'm sure that we're missing out on more capabilities.  We also have a limited use of psycopg3, hence only needing to instrument `AsyncCursor.execute`.  Nevertheless, hopefully this helps.

**Comment by Ak-x** [comment]
We have reviewed this ticket with the team and have created a Feature Request to get this through in our backlog.
cc: @ak-war

**Comment by risoms** [comment]
@Ak-x Is there any plan on support this? psycopg3 has been available for a few years now.

**Comment by gvangool** [comment]
We're curious as well about `psycopg`/`psycopg3` support.

We switched to it because of [Django 4.2's official support](https://docs.djangoproject.com/en/4.2/releases/4.2/#psycopg-3-support).

**Comment by sinwoobang** [comment]
I am into this topic.

**Comment by Ak-x** [comment]
Hey all, thank you for your interest. We have started to add this to our upcoming roadmap and will start to notify this group as we approach taking this on.

**Comment by pleasedontbelong** [comment]
Hello people ^^
Is there an update on this?

**Comment by adamJLev** [comment]
Come on newrelic, psycopg3 is not some obscure library used by a few people, and its been out for years now.
Django already said they're deprecating psycopg2, so this is way overdue. 
Hope you guys can prioritize this, thanks

**Comment by kwood** [comment]
@TimPansino @lrafeei Can someone from NewRelic comment on whether psycopg3 will be supported in the near future?

**Comment by lrafeei** [comment]
Hello--sorry about the delay.  We are looking into adding psycopg3 as a supported framework.  Unfortunately, we cannot commit to releasing that this coming quarter (but we're really hoping for the following quarter).

**Comment by msainty** [comment]
Hey New Relic or @lrafeei, Checking if there is any commitment to release this soon?

**Comment by umaannamalai** [comment]
Hey all! We have `psycopg3` support up next on our priority list in the coming quarter. We will inform you all when the release goes live.

**Comment by rodolfolottin** [comment]
> Hey all! We have `psycopg3` support up next on our priority list in the coming quarter. We will inform you all when the release goes live.

Nice! Looking forward to this.

**Comment by tarasinf** [comment]
Any updates here? We are looking for the fix.

**Comment by lrafeei** [comment]
Hi there!  Sorry about the delay on this, but there's a PR on this finally: https://github.com/newrelic/newrelic-python-agent/pull/1155
It's being reviewed now so this will definitely be out in the next release.

**Comment by rodolfolottin** [comment]
> Hi there! Sorry about the delay on this, but there's a PR on this finally: #1155 It's being reviewed now so this will definitely be out in the next release.

Thank you!

**Comment by rodolfolottin** [comment]
Nice work team! https://github.com/newrelic/newrelic-python-agent/releases/tag/v9.11.0
