### ISSUE TITLE
New Relic 7.16.0.178 started failing (sentry errors)

### ISSUE THREAD

**Issue by miguelgf** [newrelic/newrelic-python-agent#593]
**Description**
We upgraded our service from 7.14.0.177 to 7.16.0.178 and start to get the errors on Sentry:

```
InterfaceError
newrelic.hooks.database_psycopg2 in cursor
connection already closed
```

![image](https://user-images.githubusercontent.com/3419188/181456747-3b237371-9fcc-4cdd-b65a-2cfc1d5d5b65.png)

**Expected Behavior**

**Steps to Reproduce**
We are doing normal queries to the database. The process is a long running process. 

**Your Environment**
```
Name | CPython
Version | 3.8.13(3.8.13 (default, Jul 12 2022, 12:32:46)  [GCC 10.2.1 20210110])
```

Django 2.2

**Additional context**
I had to roll back to the previous version and the error dissapeared. Until I get confirmation of this being solved, can't upgrade to next version.

**Comment by Ak-x** [comment]
@miguelgf have you tried this with the latest version, if so can you confirm this issue is still appearing for you?

**Comment by miguelgf** [comment]
@Ak-x no, we didn’t try, we changed to datadog
