### ISSUE TITLE
integrations: aioredis creates coroutines that do not execute for sync operations

### ISSUE THREAD

**Issue by vishal-wadhwa** [newrelic/newrelic-python-agent#623]
**Description**

In order to record  Redis database transactions via `aioredis` client library, we upgraded the newrelic python agent from  [v7.4.0.172](https://github.com/newrelic/newrelic-python-agent/releases/tag/v7.4.0.172) to [v7.16.0.178](https://github.com/newrelic/newrelic-python-agent/releases/tag/v7.16.0.178)

Service degradation was observed as the update was rolled out in production. 
The cause was that the `newrelic` wrapped `aioredis` functions for Pipelines were failing to execute.

To me, it seems that the new `aioredis` integration is wrapping all of the functions with async and effectively returning a `coroutine` while the original implementation returns an `Awaitable` (Pipeline)  always, that need not be awaited immediately.

Since `aioredis` supports [both](https://aioredis.readthedocs.io/en/latest/api/high-level/#aioredis.client.Redis.transaction:~:text=%22Pipeline%22%5D%2C-,Union%5BAny%2C%20Awaitable%5BAny%5D%5D,-%5D%2C%0A%20%20%20%20*watches) sync and async callbacks in the transaction function, the newrelic package should too.

Refer to the reproducible example below.

**Expected Behavior**
All functions to work the same as without newrelic integrations. The functionality should not break.

**[Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results**
This log was printed to stderr when `aioredis` pipeline set was used in a transaction.
```
RuntimeWarning: coroutine '_wrap_AioRedis_method_wrapper.<locals>._nr_wrapper_AioRedis_method_' was never awaited 
```
[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

**Steps to Reproduce**
Instructions and repro here -
https://gist.github.com/vishal-wadhwa/337ff7c7e3146ede0849cbbbfff107b0

**Your Environment**
Not relevant. Reproducible in all environments.

**Additional context**
NA

**Comment by TimPansino** [comment]
We can reproduce and confirm this is an issue, we'll get a patch out soon to avoid breaking the underlying package functionality.

Unfortunately full transaction support is a bit large for a patch and would be a new feature. It will need some development time so for the time being transactions will function but won't send up any telemetry data while we work to support them.

**Comment by guillemfrancisco** [comment]
Is this really fixed? Still seeing this error with latest library release...

I'm using FastApi with aioredis to build a realtime application with pub/sub pattern. On FastApi startup I create an asyncio task that subscribes to a redis channel pattern.

However when using the latest release I'm facing similar issue as @vishal-wadhwa , I get `AttributeError: 'coroutine' object has no attribute 'psubscribe'` . But if instead I use an older version such as `newrelic==7.4.0.172` everything works perfectly!

**Comment by lrafeei** [comment]
The latest release of the agent should have a fix for this issue.  If this is still an issue for you with the latest version, we can reopen this ticket.
