### ISSUE TITLE
_bind_Producer_produce() got an unexpected keyword argument 'callback'

### ISSUE THREAD

**Issue by thsunkid** [newrelic/newrelic-python-agent#643]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

**Description**
Newrelics was broken after updating to the current latest version (`8.1.0.181`).
The error message:
>   File "/usr/local/lib/python3.9/site-packages/newrelic/hooks/messagebroker_confluentkafka.py", line 45, in wrap_Producer_produce
    topic, value, key, partition, on_delivery, timestamp, headers = _bind_Producer_produce(*args, **kwargs)
TypeError: _bind_Producer_produce() got an unexpected keyword argument 'callback'

**Steps to Reproduce**
Try the code below:
``` python
from confluent_kafka import Producer
import logging

conf = {
    "bootstrap.servers": YOUR_KAFKA_BROKER_URL,
    "security.protocol": "SASL_SSL",
    "sasl.mechanisms": "PLAIN",
    "sasl.username": YOUR_KAFKA_API_KEY,
    "sasl.password": YOUR_KAFKA_API_SECRET,
}

def acked(err, msg):
    if err is not None:
        logging.error(
            "Failed to deliver message: %s: %s" % (str(msg), str(err))
        )
producer = Producer(conf)
producer.produce(
    topic,
    key=key,
    value=value,
    callback=acked,
)

```

**Your Environment**
python 3.8
confluent-kafka v1.9.2
newrelic v8.1.0.181

**Comment by lrafeei** [comment]
Thank you for bringing this to our attention.  We fixed this and will provide this in our next release.
