### ISSUE TITLE
Instrumented libraries not reported when called from run_in_executor

### ISSUE THREAD

**Issue by GabrielCappelli** [newrelic/newrelic-python-agent#657]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

**Description**
Instrumentation of module works, but if call is wrapped in loop_run_in_executor then it no longer works.

For example, using mysqlclient database, this works fine:
```
database.connect().execute("select sleep(2)") # Shows up as MySQL on NR
```

But if I use run_in_executor then it's not detected properly:
```
await asyncio.get_running_loop().run_in_executor(
    None, lambda: database.connect().execute("select sleep(2)")
) # Shows up as Python on  NR
```

**Expected Behavior**

NewRelic would detect MySQL calls regardless of whether they were executed in `run_in_executor`

**[Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results**

**Steps to Reproduce**

Use `run_in_executor` to execute code for a instrumented library

**Your Environment**

Python 3.10.7

sanic 22.9.0

newrelic 8.2.1

**Additional context**

Both transaction as they were reported in NR:
![image](https://user-images.githubusercontent.com/6148081/195166132-c6883fd6-ad6d-47af-b31c-8485b3b92a8c.png)

**Comment by Ak-x** [comment]
This is currently expected behavior; however this does fit into a feature request category.  Our PM is aware of this and we have a FR to review with the request here.
