### ISSUE TITLE
Deprecation of add_custom_parameter?

### ISSUE THREAD

**Issue by daveisfera** [newrelic/newrelic-python-agent#670]
It feels really odd that [`add_custom_parameter` is deprecated](https://github.com/newrelic/newrelic-python-agent/releases/tag/v8.3.0) when it's still in the documentation and I can't find any info on the suggested replacement, so is that available somewhere?

For example, this is the documentation I could find and it shows `add_customer_parameter`:
https://docs.newrelic.com/docs/apm/agents/python-agent/python-agent-api/addcustomparameter-python-agent-api/
https://docs.newrelic.com/docs/data-apis/custom-data/custom-events/collect-custom-attributes/

**Comment by TimPansino** [comment]
The documentation page isn't updated yet, it should be live this afternoon.

The API was just renamed to `add_custom_attribute` and `add_custom_attributes` instead of parameter to match other agents. The existing APIs will continue to work as a pass through with a deprecation warning.

**Comment by daveisfera** [comment]
Could that info be provided somewhere? Maybe in the release notes?

**Comment by umaannamalai** [comment]
We have tweaked the [release notes](https://docs.newrelic.com/docs/release-notes/agent-release-notes/python-release-notes/python-agent-80300) to clarify that the original API has been renamed. The API guide docs regarding this change are undergoing review from our docs team and should be up once that process has completed.

**Comment by daveisfera** [comment]
Could that be updated in the release notes here on GitHub as well? I typically just see them here and imagine that's true for a lot of developers (i.e. that documentation on the website is nice but typically not where developers will look for it)

**Comment by umaannamalai** [comment]
Definitely, we totally understand and appreciate the feedback! Once our release notes go live on the docs site, we update the GitHub release with a link to the notes. The [v8.3.0 release](https://github.com/newrelic/newrelic-python-agent/releases/tag/v8.3.0) has now been updated.
