### ISSUE TITLE
AttributeError: module 'newrelic.agent' has no attribute 'NewRelicContextFormatter'

### ISSUE THREAD

**Issue by jfurton** [newrelic/newrelic-python-agent#673]
**Description**

getting this error:  

```AttributeError: 'newrelic.agent' has no attribute 'NewRelicContextFormatter' not visible anymore```

with #655 seems like NewRelicContextFormatter was commented out. 

https://github.com/newrelic/newrelic-python-agent/blob/ca420b327dfce0093daab58461a583e5573d1fce/newrelic/agent.py#L19

https://docs.newrelic.com/docs/logs/logs-context/configure-logs-context-python/ still shows

```from newrelic.agent import NewRelicContextFormatter``` 

as the way to use it, not sure if I missed some deprecation / removal. 
 

**Your Environment**
 python3.11

**Comment by TimPansino** [comment]
Sorry about that, looks like it was commented out by mistake and slipped through. We're running a release today so we'll get that fixed in the latest version.
