### ISSUE TITLE
integrate newrelic with starlite

### ISSUE THREAD

**Issue by indra-an** [newrelic/newrelic-python-agent#693]
Hi,
I`ve tried to integrate starlite with newrelic,
but getting error

`CIMultiDict keys should be either str or subclasses of str`

could you guys help me why this happen?

this is my sample project for reproduce this case
[https://github.com/indra-an/starlite-newrelic](https://github.com/indra-an/starlite-newrelic)

**Comment by Ak-x** [comment]
Hello, this topic would be best suited for [New Relic Support](https://discuss.newrelic.com/)
