### ISSUE TITLE
Agent breaks confluent_kafka's Producer.produce (v8.5.0)

### ISSUE THREAD

**Issue by ollandos** [newrelic/newrelic-python-agent#743]
confluent_kafka Procuder.produce fails in newrilc's messagebroker_confluentkafka.py

**Description**
```
AttributeError

'Sentinel' object has no attribute 'generate_request_headers'
```
**[Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results**
```python
        operation="Produce",
        destination_type="Topic",
        destination_name=topic or "Default",
        source=wrapped,
    ) as trace:
        dt_headers = {k: v.encode("utf-8") for k, v in trace.generate_request_headers(transaction)}  # This line throws error
        # headers can be a list of tuples or a dict so convert to dict for consistency.
        dt_headers.update(dict(headers) if headers else {})
        try:
            return wrapped(topic, headers=dt_headers, *args, **kwargs)
        except Exception as error:
```

**Expected Behavior**
Should work.

**[Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results**
-

**Steps to Reproduce**
Cannot reproduce consistently. I see it popping up on sentry.io

**Your Environment**
The docker image that is running is this:
```
python:3.9-slim-bullseye
```

**Additional context**
Had to rollback to `8.1.0.180` before the introduction of the kafka wrapper.

**Comment by hmstepanek** [comment]
This has been fixed in v9.4.0.
