### ISSUE TITLE
[Python] - Lambda Timeout - GraphQL Introspection Query 

### ISSUE THREAD

**Issue by Mainian** [newrelic/newrelic-python-agent#748]
## Description

Not sure if this issue belongs here or in [newrelic/newrelic-python-agent](https://github.com/newrelic/newrelic-python-agent)

After processing a [Graphql Introspection query](https://github.com/graphql-python/graphql-core/blob/main/docs/usage/introspection.rst), the Lambda Function times out and telemetry data is not forwarded to New Relic. 

## Steps to Reproduce

With a Lambda Function running Graphql Server, make a graphql introspection query. The function will return a response, but the Lambda will not be available to process another request until it's timeout duration is reached.

Example graphql request:

```
{
  __schema {
    types {
      name
    }
  }
}
```

## Expected Behaviour

Lambda function does not timeout and the New Relic Agent forwards telemetry data.

## Relevant Logs / Console output

Sample log file:

```
2023-01-27T11:59:01.120-05:00 | START RequestId: 17026805-857a-4683-936e-f4b7fede3ea5 Version: 60
2023-01-27T11:59:01.618-05:00 | [NR_EXT] Sent 1/1 New Relic function log batches successfully in 45.202ms (41ms to transmit 9.2kB).

...

2023-01-27T12:00:00.973-05:00 | END RequestId: 17026805-857a-4683-936e-f4b7fede3ea5
2023-01-27T12:00:00.973-05:00 | REPORT RequestId: 17026805-857a-4683-936e-f4b7fede3ea5 Duration: 59851.68 ms Billed Duration: 59852 ms Memory Size: 1536 MB Max Memory Used: 219 MB Init Duration: 3642.79 ms
```

## Your Environment

AWS Lambda - Python 3.8
New Relic Lambda Layer 

## Additional context

The Python New Relic agent [explicitly ignores](https://github.com/newrelic/newrelic-python-agent/blob/0db5fee1e5d44b0791dc517ac9f5d88d1240a340/newrelic/hooks/framework_graphql.py#L137) GraphQL introspection queries transactions.

Un-ignoring the transaction does not cause the Lambda Function to timeout and telemetry data is forwarded:

```
        transaction = newrelic.agent.current_transaction(active_only=False)
        transaction.ignore_transaction = False
```

**Comment by Mainian** [comment]
Issue #280 and it's [pull request](https://github.com/newrelic/newrelic-python-agent/pull/290) introduced this issue into the Lambda Layer. 

@TimPansino 
I should also point out that, that this affects GraphQL operations that also include an introspection query, while probably rare, this is valid per the GraphQL spec. As leaving introspection on, and not tracing introspection requests is the intent of the original issue, it seems a possible solution is to add an environment variable to only ignore introspection queries.

**Comment by mdwint** [comment]
I have observed the same behaviour outside of GraphQL.

`newrelic.agent.ignore_transaction()` causes any Lambda function that uses the [New Relic AWS Lambda Extension](https://github.com/newrelic/newrelic-lambda-extension) to hang until it times out:

```python
import newrelic.agent

def lambda_handler(event, context):
    newrelic.agent.ignore_transaction()
```

**Comment by Mainian** [comment]
@mdwint 
Technically, I probably should have opened two separate issues. This one for graphql introspection telemetry data. 

And a separate issue to specifically address the lambda timeout problem. This [topic](https://forum.newrelic.com/s/hubtopic/aAX8W0000008cTPWAY/new-relic-extension-integrated-lambda-timing-out) also has some information.

**Comment by hmstepanek** [comment]
https://github.com/newrelic/newrelic-python-agent/pull/783 fixes this issue if you set the following environment variable:
```
NEW_RELIC_INSTRUMENTATION_GRAPHQL_CAPTURE_INTROSPECTION_QUERIES = True
```
