### ISSUE TITLE
Issue with interface wrapper on nonstandard Gunicorn based Webapp

### ISSUE THREAD

**Issue by goluukfgobea** [newrelic/newrelic-python-agent#772]
**Description**
Hello, we are using Newrelic with Odoo, which has a gunicorn based webapp (using a slightly modified werkzeug as a webserver, which is the same flask uses) 

The issue is not around python code but around the js script downloaded.

Odoo uses a JS interface for its webapp which edits promises with a new function called guardedCatch, we had a huge issue with the interface as in the latest version of new relic js, the js agent Wraps the promise native implementation and generates a new implementation with a function that has the promise inside it. 

This generates a big issue around Odoo's implementation, as the function works wonderful when using new Promise(), but it does not work when using an async function as Odoo edited the newly created object by neew relic and not the Promise itslef due to the new relic agent.

This generates a guardedCatch is not a function error, as effectively is only defined on the newRelic modified promise.

**Expected Behavior**
New Relic Js agent shouldn be modifiying native elements constructors, as it can cause unexpected behaviour like this. Promise should still return a promise whether it is called on async function, or new Promise

**[Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results**
Error:
Rastreo de error:
TypeError: Unhandled Promise Rejection: view.getController(...).then(...).guardedCatch is not a function
    at https://operations.goluuk.com/web/content/81279-50bc91d/web.assets_backend.js:456:911
    at nrWrapper (https://operations.goluuk.com/web:6:16196)
    at new Promise (<anonymous>)
    at new Promise (https://operations.goluuk.com/web:6:21087)
    at Class._createViewController (https://operations.goluuk.com/web/content/81279-50bc91d/web.assets_backend.js:456:721)
    at https://operations.goluuk.com/web/content/81279-50bc91d/web.assets_backend.js:461:169
    at nrWrapper (https://operations.goluuk.com/web:6:16196)

**Steps to Reproduce**
Add new relic to a webapp.
Generate an interface that modifies the Promise object with a new function.
Call the promise function from both new Promise.function and function.then().function
The async function won't have the newly created function.

**Your Environment**
The new relic version is the latest package.

**Comment by TimPansino** [comment]
Hello, since this is about the automatically injected New Relic Browser Agent, can you redirect this issue to https://github.com/newrelic/newrelic-browser-agent? The team that maintains the browser agents should be able to assist.

**Comment by goluukfgobea** [comment]
Thks!
