### ISSUE TITLE
NoneType object has no attribute settings

### ISSUE THREAD

**Issue by erry-takumi** [newrelic/newrelic-python-agent#786]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

**Description**
[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )

This broke our production build. Not every, but lots of requests failed due to newrelic framework_graphql

AttributeError: 'NoneType' object has no attribute 'settings'
  File "promise/promise.py", line 87, in try_catch
    return (handler(*args, **kwargs), None)
  File "graphql/execution/executor.py", line 127, in promise_executor
    return execute_operation(exe_context, exe_context.operation, root_value)
  File "newrelic/hooks/framework_graphql.py", line 108, in wrap_execute_operation
    settings = transaction.settings

**Expected Behavior**
[NOTE]: # ( Tell us what you expected to happen. )

It doesn't crash :)

**[Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results**
[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

**Steps to Reproduce**
[NOTE]: # ( Please be as specific as possible. )
[TIP]:  # ( Link a sample application that demonstrates the issue. )
Any graphql query

**Your Environment**
[TIP]:  # ( Include as many relevant details about your environment as possible including the running version of New Relic software and any relevant configurations. )

newrelic 8.7.1 (This did NOT happen on 8.7.0)
graphene 2.1.6

**Additional context**
[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )

I know We're on an old version of graphene,  but still, one would hope patch version upgrades don't have breaking changes 🤣

**Comment by TimPansino** [comment]
Hello @erry-takumi, sorry about that. I've opened a PR to guard that settings lookup to prevent this. If you back down to 8.7.0 for the time being you shouldn't see any issues. We'll put a patch version out to address this as soon as we can.
