### ISSUE TITLE
Does newrelic support python thrift server？

### ISSUE THREAD

**Issue by x931890193** [newrelic/newrelic-python-agent#827]
### Is your feature request related to a problem? Please describe.
Does newrelic support python thrift server？

### Feature Description
Does newrelic support python thrift server？

### Describe Alternatives
Does newrelic support python thrift server？

### Additional context
Does newrelic support python thrift server？

### Priority
Does newrelic support python thrift server？

**Comment by lrafeei** [comment]
Hello--No, the Python Thrift server is not supported by New Relic

**Comment by x931890193** [comment]
> Hello--No, the Python Thrift server is not supported by New Relic

Many Thx
