### ISSUE TITLE
newrelic segments of RedisCluster in redis-py didn't be captured by agent

### ISSUE THREAD

**Issue by holyachon** [newrelic/newrelic-python-agent#834]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

**Description**
[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )
I know that newrelic-python-agent officially supports [redis-py](https://github.com/redis/redis-py) library.
However, when using RedisCluster of redis-py (for cluster mode), it does not work. Not only redis-related segments are not visible in the "transaction" tab, but also `redis` are not visible in the "Database" tab.

**Expected Behavior**
[NOTE]: # ( Tell us what you expected to happen. )

Even if using `RedisCluster` in redis-py, metrics are shown in Database tab. (like below image which is using `Redis`, not cluster)
<img width="419" alt="image" src="https://github.com/newrelic/newrelic-python-agent/assets/3615955/7de12c0d-f4e8-4db3-969c-6e25619aec7b">

**[Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results**
[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

**Steps to Reproduce**
[NOTE]: # ( Please be as specific as possible. )
[TIP]:  # ( Link a sample application that demonstrates the issue. )
in web application's request handler,
```
from gevent import monkey
monkey.patch_all()
from redis.cluster import RedisCluster

client = RedisCluster(
    host="localhost",
)

client.set("a", "b")
a = client.get("a")
```

**Your Environment**
[TIP]:  # ( Include as many relevant details about your environment as possible including the running version of New Relic software and any relevant configurations. )
```
gevent = "21.12.0"
redis = {version = "^4.5.5", extras = ["hiredis"]}
newrelic = "8.8.0"
```
This issue occurs with or without hiredis. And I tested w/ several newrelic versions 6.10.0.165, 7.16.0.178, and 8.8.0 (latest).

**Additional context**
[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )
I guess that agent needs a hook for Redis Cluster (module : `redis.cluster`)
```
_process_module_definition("redis.client", "newrelic.hooks.datastore_redis", "instrument_redis_client")
```

**Comment by lrafeei** [comment]
Hello--We recently [released v8.9.0](https://github.com/newrelic/newrelic-python-agent/releases/tag/v8.9.0) that has support for RedisCluster.  I will close this ticket, but if something is not working for you with RedisCluster, we can reopen the ticket.
