### ISSUE TITLE
TypeError: super(type, obj): obj must be an instance or subtype of type!

### ISSUE THREAD

**Issue by x931890193** [newrelic/newrelic-python-agent#889]
HI @lrafeei ~

&nbsp;  There is something wrong with `newrelic-5.4.134`

## env 
-> python2.7
-> newrelic-5.4.134

When web framework enable DEBUG mode， we use `reload` to watch code change,  when code changed, there is some wrong!

![image](https://github.com/newrelic/newrelic-python-agent/assets/24632574/d375358a-8648-4931-85d1-ace97098a307)

Is there anyway can fix it or new version newrelic already fixed it?
Many thanks! 😃

**Comment by lrafeei** [comment]
Hello--have you tried a newer version?  I ask because that version is over 3 years old and there have been some changes to the files shown in the stack trace (including some Python 2.7 compatibility fixes).  If updating to a newer version does not work for you, we can take a deeper dive into this.

**Comment by x931890193** [comment]
> 

Thanks  I will try to use new version～

**Comment by Ak-x** [comment]
Hello @x931890193 we are closing this issue out - if you continue to see issues please re-open.
