### ISSUE TITLE
SSL Errors record-deploy; CA File out of date, and bad ca check.

### ISSUE THREAD

**Issue by Wrhector** [newrelic/newrelic-python-agent#906]
Yesterday, the certificate for `api.newrelic.com` was updated to a Let's Encrypt certificate. The Python agent uses this hostname for `record-deploy`.
After this change we started getting SSL errors when trying to use `record-deploy`, even though Python and curl have no issues:
```
newrelic.packages.urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)
```

Doing some debugging we found two problems:

**Bundled CA file needs updating**
The file  https://github.com/newrelic/newrelic-python-agent/blob/main/newrelic/common/cacert.pem is out of date. It is missing the  **ISRG Root X1** ca that Let's Encrypt, and therefore `api.newrelic.com` uses.

**System CA File check is incorrect**
We were confused why the fallback bundle was even being used. We found that on Ubuntu, the `cafile` returns `None` for the `ssl.get_default_verify_paths` check, and only returns `capath`:
```bash
# python3.10 -c "import ssl; print(ssl.get_default_verify_paths())"
DefaultVerifyPaths(cafile=None, capath='/usr/lib/ssl/certs', openssl_cafile_env='SSL_CERT_FILE', openssl_cafile='/usr/lib/ssl/cert.pem', openssl_capath_env='SSL_CERT_DIR', openssl_capath='/usr/lib/ssl/certs')
```

However the code here: https://github.com/newrelic/newrelic-python-agent/blob/main/newrelic/common/agent_http.py#L266 only checks the path:
```python
               if not verify_path.cafile:
                    ca_bundle_path = certs.where()
                    internal_metric(
                        "Supportability/Python/Certificate/BundleRequired", 1
                    )
```

It should be;
```python
               if not verify_path.cafile and not verify_path.capath:
                    ca_bundle_path = certs.where()
                    internal_metric(
                        "Supportability/Python/Certificate/BundleRequired", 1
                    )
```

Which fixes the issue to use the system ceritficate store, which is more up to date than the bundle.

**Your Environment**
Ubuntu 20.04, 18.04; Python 3.7-3.10

**Comment by hmstepanek** [comment]
This fix is available in https://pypi.org/project/newrelic/8.11.0/.

**Comment by Wrhector** [comment]
@hmstepanek Thanks, looks like the fallback cert wasn't update though? In case people don't have any local certs.
