### ISSUE TITLE
Increased CPU usage since 8.11.0 / 8.10.1 release

### ISSUE THREAD

**Issue by khink** [newrelic/newrelic-python-agent#927]
After we upgraded from 8.10.0 to 8.11.0, we noticed an increase in CPU usage:
![image](https://github.com/newrelic/newrelic-python-agent/assets/179642/daab745b-ad56-462f-9663-53249a9746f0)
![image](https://github.com/newrelic/newrelic-python-agent/assets/179642/cbe41cdc-dab6-4c0f-9c8e-080b72865360)

Yesterday, we went back to 8.10.0 on TST and it seemed to reduce CPU usage:
![image](https://github.com/newrelic/newrelic-python-agent/assets/179642/f8e9e2a8-c488-4942-b475-c5d20dd61f18)

I'm hoping to get some pointers for profiling this issue, i can spend some time. So far we seem to be the only ones experiencing this, although #918 might be related.

From https://docs.newrelic.com/docs/release-notes/agent-release-notes/python-release-notes/python-agent-81100/ it's not clear which change may have caused this. It might also have been in 8.10.1, which we skipped. We also upgraded to 9.0.0, which shows the same increased CPU usage. 

**Your Environment**

We use newrelic in an e-commerce application based on Django-Oscar and Django REST Framework. 

We are hosting this on Amazon ECS, graphs are from its "Health and service" dashboard.

We have TST, ACC and PRD environments, and we see the issue on all three envs. The TST env is logging at DEBUG level, so its logs might contain useful info, if we knew what to look for. Searching on "newrelic" only gives messages like `newrelic.config DEBUG - register module ('rest_framework.views', 'newrelic.hooks.component_djangorestframework', 'instrument_rest_framework_views')`, which happens after the application starts up.

**Comment by natemoser** [comment]
I posted our findings on the [#918](https://github.com/newrelic/newrelic-python-agent/issues/918) issue you lined to. We're seeing similar things between 8.10.0 and 8.10.1. 

I was able to use New Relic's thread profiler to show that the increase was coming from additional time in `importlib:metadata`, which led me to suspect the newrelic update, which led me here.

**Comment by whyscream** [comment]
Related commit that introduced the problem (I guess): https://github.com/newrelic/newrelic-python-agent/commit/7d76243c305065ac7895ed9d624d5849d124ea46

**Comment by alexandre-paroissien** [comment]
Noticed the same issue, seems it was only affecting celery pods

The CPU usage went up significantly when upgrading the library, and back down after downgrading 

<img width="910" alt="image" src="https://github.com/newrelic/newrelic-python-agent/assets/34052139/f45b85b6-86b6-4eb1-9a6d-2e3034226a42">

**Comment by alexandre-paroissien** [comment]
Upgraded to 9.2.0 and the issue is no longer there 👍 

<img width="921" alt="image" src="https://github.com/newrelic/newrelic-python-agent/assets/34052139/95ac5f25-10e3-4021-a47a-77c51fdf8922">

**Comment by khink** [comment]
Same here, we upgraded to 9.2.0 this past week (from 8.10.0 which we pinned) and CPU use is normal. Thanks to all contributors!
