### ISSUE TITLE
Unable to join Slack to ask some questions about contributing

### ISSUE THREAD

**Issue by nburns** [newrelic/newrelic-python-agent#968]
**Description**
the slack link is broken in the CONTRIBUTING.rst file: https://github.com/newrelic/newrelic-python-agent/blob/main/CONTRIBUTING.rst#slack

**Expected Behavior**
I'd be able to join a slack and ask some questions about work related to https://github.com/newrelic/newrelic-python-agent/issues/952

**Steps to Reproduce**
visit the link in the description above and click the slack link

**Your Environment**
safari

**Additional context**
trying to run the tests in the devcontainer does not work, and I'm wondering if I'm missing some setup instructions:
```
> docker exec -it --workdir /workspaces/newrelic-python-agent 35a3a60c14cd /bin/bash
```

```
vscode@linuxkit-66f0adc78c76:/workspaces/newrelic-python-agent/tests$ tox -c tox.ini -e datastore_aiomysql
/home/vscode/.pyenv/shims/tox: line 8: /root/.pyenv/libexec/pyenv: Permission denied
```

**Comment by TimPansino** [comment]
That workspace looks like it's been deleted, I'm not sure why it's gone.

As far as the devcontainer goes, looks like the permissions issue wasn't fixed all the way. I'll fix that.
